### ISSUE TITLE
download please (not sourcecode)

### ISSUE THREAD

**Issue by ff6f8d68** [Arathain/LodestoneLib-Quilt#10]

**Comment by ghost** [comment]
Any mods you need this for should have it automatically bundled in. (otherwise at least say for what version)

**Comment by ff6f8d68** [comment]
the mod I´m using: [https://ko-fi.com/post/Expedition-Airship-mod-for-Minecraft-1-19-2-X7X0GY8M8#checkoutModal](https://ko-fi.com/post/Expedition-Airship-mod-for-Minecraft-1-19-2-X7X0GY8M8#checkoutModal)

**Comment by ff6f8d68** [comment]
fixed I have installed normal Fabric API instead of Quilted Fabric API.
other error can you explain this: [https://mclo.gs/eqCUwae](https://mclo.gs/eqCUwae)

**Comment by ghost** [comment]
Oh I had that in my dev env just this morning, try installing Satin API

**Comment by ff6f8d68** [comment]
after installing Satin API it´s this error now: https://mclo.gs/49qgdv0

**Comment by ff6f8d68** [comment]
the mods I installed
![Screenshot 2024-04-04 at 16 54 56](https://github.com/Arathain/LodestoneLib-Quilt/assets/138153020/d4236b62-38d4-48de-90ac-a24246126152)

**Comment by Arathain** [comment]
This is an API mod that should be bundled with any mod you're using it with - a download will not be provided, especially considering the fact that this is effectively abandonware.
