### ISSUE TITLE
Issue with licensing

### ISSUE THREAD

**Issue by emneo-dev** [Arathain/LodestoneLib-Quilt#6]
In the readme it is written `The license is presented in good faith`.
What does that mean?
Do I have to follow what the LICENSE file tells me or do I have to follow the two lines in the README requiring a authorization for some use of that source code?

**Comment by Arathain** [comment]
technically, you can just go with the license
practically, if you want to port the mod to fabric it'd be best to ask the developers of the forge version just to be good-faith; we've had some unfortunate incidents, but it hasn't gotten grave enough to where I'd split the project and whatnot.
